spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: https://dev-27548664.okta.com/oauth2/default
        registration:
          okta:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope: openid,profile,email

resourceServer:
  url: http://localhost:8081
  helloPath: /api/resource/hello